name: lamaofficial
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.13.0
  - aiohttp=3.7.4.post0
  - antlr-python-runtime=4.8
  - async-timeout=3.0.1
  - attrs=21.2.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.7.5
  - cachetools=4.2.2
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.0.1
  - cloudpickle=2.0.0
  - coverage=5.5
  - cryptography=3.4.7
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - cython=0.29.24
  - cytoolz=0.11.0
  - dask-core=1.1.4
  - dataclasses=0.8
  - dbus=1.13.18
  - decorator=5.0.9
  - easydict=1.9
  - expat=2.4.1
  - ffmpeg=4.2.2
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fsspec=2021.8.1
  - future=0.18.2
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=1.33.0
  - google-auth-oauthlib=0.4.4
  - grpcio=1.36.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hydra-core=1.1.0
  - icu=58.2
  - idna=3.2
  - idna_ssl=1.1.0
  - imageio=2.9.0
  - importlib-metadata=4.8.1
  - importlib_resources=5.2.0
  - intel-openmp=2021.3.0
  - joblib=1.0.1
  - jpeg=9b
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libvpx=1.7.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2021.3.0
  - multidict=5.1.0
  - ncurses=6.2
  - nettle=3.7.3
  - networkx=2.2
  - ninja=1.10.2
  - numpy=1.19.5
  - oauthlib=3.1.1
  - olefile=0.46
  - omegaconf=2.1.1
  - openh264=2.1.0
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.1.5
  - pcre=8.45
  - pillow=8.3.1
  - pip=21.0.1
  - protobuf=3.17.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pyjwt=2.1.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.6.13
  - python-dateutil=2.8.2
  - python_abi=3.6
  - pytz=2021.1
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - qt=5.9.7
  - readline=8.1
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-image=0.17.2
  - scikit-learn=0.24.2
  - scipy=1.5.3
  - setuptools=58.0.4
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.36.0
  - tabulate=0.8.9
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.6.0
  - threadpoolctl=2.2.0
  - tifffile=2020.10.1
  - tk=8.6.11
  - toolz=0.11.1
  - tqdm=4.62.2
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - urllib3=1.26.6
  - werkzeug=2.0.1
  - wheel=0.37.0
  - x264=1!157.20191217
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - albumentations==0.5.2
    - braceexpand==0.1.7
    - imgaug==0.4.0
    - kornia==0.5.0
    - opencv-python==4.5.3.56
    - opencv-python-headless==4.5.3.56
    - shapely==1.7.1
    - webdataset==0.1.76
    - wldhx-yadisk-direct==0.0.6
